---
http_interactions:
- request:
    method: post
    uri: http://win7dev:8989/SampleService/RubyOData.svc/Categories
    body:
      encoding: UTF-8
      string: '{"Name":"Test Category","AuditFields":{"CreatedBy":"Machinist"}}'
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Accept:
      - '*/*; q=0.5, application/xml'
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Cache-Control:
      - no-cache
      Content-Length:
      - '1247'
      Content-Type:
      - application/atom+xml;type=entry;charset=utf-8
      Location:
      - http://win7dev:8989/SampleService/RubyOData.svc/Categories(1)
      Server:
      - Microsoft-IIS/7.5
      Set-Cookie:
      - ASP.NET_SessionId=55gxqunf3rkerrwz3hw12kyz; path=/; HttpOnly
      X-Content-Type-Options:
      - nosniff
      Dataserviceversion:
      - 1.0;
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Tue, 29 Apr 2014 01:18:01 GMT
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="utf-8"?><entry xml:base="http://win7dev:8989/SampleService/RubyOData.svc/"
        xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices"
        xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss"
        xmlns:gml="http://www.opengis.net/gml"><id>http://win7dev:8989/SampleService/RubyOData.svc/Categories(1)</id><category
        term="RubyODataService.Category" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"
        /><link rel="edit" title="Category" href="Categories(1)" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Products"
        type="application/atom+xml;type=feed" title="Products" href="Categories(1)/Products"
        /><title /><updated>2014-04-29T01:18:01Z</updated><author><name /></author><content
        type="application/xml"><m:properties><d:Id m:type="Edm.Int32">1</d:Id><d:Name>Test
        Category</d:Name><d:AuditFields m:type="RubyODataService.AuditFields"><d:CreateDate
        m:type="Edm.DateTime">2014-04-29T01:18:01.238Z</d:CreateDate><d:ModifiedDate
        m:type="Edm.DateTime">2014-04-29T01:18:01.238Z</d:ModifiedDate><d:CreatedBy>Machinist</d:CreatedBy></d:AuditFields></m:properties></content></entry>
    http_version: 
  recorded_at: Tue, 29 Apr 2014 01:18:01 GMT
- request:
    method: get
    uri: http://win7dev:8989/SampleService/RubyOData.svc/Categories(1)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Accept:
      - '*/*; q=0.5, application/xml'
      Accept-Encoding:
      - gzip, deflate
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Content-Length:
      - '1245'
      Content-Type:
      - application/atom+xml;type=entry;charset=utf-8
      Server:
      - Microsoft-IIS/7.5
      Set-Cookie:
      - ASP.NET_SessionId=4f1i4dodyczgqwgul1e1m242; path=/; HttpOnly
      X-Content-Type-Options:
      - nosniff
      Dataserviceversion:
      - 1.0;
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Tue, 29 Apr 2014 01:18:01 GMT
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="utf-8"?><entry xml:base="http://win7dev:8989/SampleService/RubyOData.svc/"
        xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices"
        xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss"
        xmlns:gml="http://www.opengis.net/gml"><id>http://win7dev:8989/SampleService/RubyOData.svc/Categories(1)</id><category
        term="RubyODataService.Category" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"
        /><link rel="edit" title="Category" href="Categories(1)" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Products"
        type="application/atom+xml;type=feed" title="Products" href="Categories(1)/Products"
        /><title /><updated>2014-04-29T01:18:01Z</updated><author><name /></author><content
        type="application/xml"><m:properties><d:Id m:type="Edm.Int32">1</d:Id><d:Name>Test
        Category</d:Name><d:AuditFields m:type="RubyODataService.AuditFields"><d:CreateDate
        m:type="Edm.DateTime">2014-04-29T01:18:01.237</d:CreateDate><d:ModifiedDate
        m:type="Edm.DateTime">2014-04-29T01:18:01.237</d:ModifiedDate><d:CreatedBy>Machinist</d:CreatedBy></d:AuditFields></m:properties></content></entry>
    http_version: 
  recorded_at: Tue, 29 Apr 2014 01:18:01 GMT
- request:
    method: post
    uri: http://win7dev:8989/SampleService/RubyOData.svc/Products
    body:
      encoding: UTF-8
      string: '{"Name":"Widget 0060","Description":"Test Widget","Price":"75.50","Category":{"Name":"Category
        0062","AuditFields":{"CreatedBy":"Machinist"}},"AuditFields":{"CreatedBy":"Machinist"}}'
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Accept:
      - '*/*; q=0.5, application/xml'
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Cache-Control:
      - no-cache
      Content-Length:
      - '1434'
      Content-Type:
      - application/atom+xml;type=entry;charset=utf-8
      Location:
      - http://win7dev:8989/SampleService/RubyOData.svc/Products(1)
      Server:
      - Microsoft-IIS/7.5
      Set-Cookie:
      - ASP.NET_SessionId=vft01ytgordciawqqnjilixn; path=/; HttpOnly
      X-Content-Type-Options:
      - nosniff
      Dataserviceversion:
      - 1.0;
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Tue, 29 Apr 2014 01:18:01 GMT
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="utf-8"?><entry xml:base="http://win7dev:8989/SampleService/RubyOData.svc/"
        xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices"
        xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss"
        xmlns:gml="http://www.opengis.net/gml"><id>http://win7dev:8989/SampleService/RubyOData.svc/Products(1)</id><category
        term="RubyODataService.Product" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"
        /><link rel="edit" title="Product" href="Products(1)" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Category"
        type="application/atom+xml;type=entry" title="Category" href="Products(1)/Category"
        /><title /><updated>2014-04-29T01:18:01Z</updated><author><name /></author><content
        type="application/xml"><m:properties><d:Id m:type="Edm.Int32">1</d:Id><d:Name>Widget
        0060</d:Name><d:Description>Test Widget</d:Description><d:Price m:type="Edm.Decimal">75.50</d:Price><d:DiscontinuedDate
        m:type="Edm.DateTime" m:null="true" /><d:CategoryId m:type="Edm.Int32">1</d:CategoryId><d:AuditFields
        m:type="RubyODataService.AuditFields"><d:CreateDate m:type="Edm.DateTime">2014-04-29T01:18:01.4876Z</d:CreateDate><d:ModifiedDate
        m:type="Edm.DateTime">2014-04-29T01:18:01.4876Z</d:ModifiedDate><d:CreatedBy>Machinist</d:CreatedBy></d:AuditFields></m:properties></content></entry>
    http_version: 
  recorded_at: Tue, 29 Apr 2014 01:18:01 GMT
- request:
    method: get
    uri: http://win7dev:8989/SampleService/RubyOData.svc/Products(1)
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Accept:
      - '*/*; q=0.5, application/xml'
      Accept-Encoding:
      - gzip, deflate
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Content-Length:
      - '1430'
      Content-Type:
      - application/atom+xml;type=entry;charset=utf-8
      Server:
      - Microsoft-IIS/7.5
      Set-Cookie:
      - ASP.NET_SessionId=tpnfh0wq0ngkcp0jjgtloce0; path=/; HttpOnly
      X-Content-Type-Options:
      - nosniff
      Dataserviceversion:
      - 1.0;
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Tue, 29 Apr 2014 01:18:01 GMT
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="utf-8"?><entry xml:base="http://win7dev:8989/SampleService/RubyOData.svc/"
        xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices"
        xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss"
        xmlns:gml="http://www.opengis.net/gml"><id>http://win7dev:8989/SampleService/RubyOData.svc/Products(1)</id><category
        term="RubyODataService.Product" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"
        /><link rel="edit" title="Product" href="Products(1)" /><link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Category"
        type="application/atom+xml;type=entry" title="Category" href="Products(1)/Category"
        /><title /><updated>2014-04-29T01:18:01Z</updated><author><name /></author><content
        type="application/xml"><m:properties><d:Id m:type="Edm.Int32">1</d:Id><d:Name>Widget
        0060</d:Name><d:Description>Test Widget</d:Description><d:Price m:type="Edm.Decimal">75.50</d:Price><d:DiscontinuedDate
        m:type="Edm.DateTime" m:null="true" /><d:CategoryId m:type="Edm.Int32">1</d:CategoryId><d:AuditFields
        m:type="RubyODataService.AuditFields"><d:CreateDate m:type="Edm.DateTime">2014-04-29T01:18:01.487</d:CreateDate><d:ModifiedDate
        m:type="Edm.DateTime">2014-04-29T01:18:01.487</d:ModifiedDate><d:CreatedBy>Machinist</d:CreatedBy></d:AuditFields></m:properties></content></entry>
    http_version: 
  recorded_at: Tue, 29 Apr 2014 01:18:01 GMT
recorded_with: VCR 2.5.0
